---
- name: Instalar Apache en DEVASC puerto 9999
  hosts: localhost
  become: yes

  tasks:
    - name: Instalar Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Configurar Apache en puerto 9999
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen '
        line: 'Listen 9999'

    - name: Configurar VirtualHost en puerto 9999
      replace:
        path: /etc/apache2/sites-enabled/000-default.conf
        regexp: '<VirtualHost \*:80>'
        replace: '<VirtualHost *:9999>'

    - name: Reiniciar Apache
      service:
        name: apache2
        state: restarted
